# Generated by Django 5.1.7 on 2025-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.IntegerField(),
        ),
    ]
